#pragma once

// 驱动名称与符号链接
#define DUMMY_IOCTL_DEVICE_NAME    L"\\Device\\DummyDriverIoctl"
#define DUMMY_IOCTL_SYM_LINK       L"\\DosDevices\\DummyDriverIoctl"

// IOCTL 定义
#define IOCTL_DUMMY_HELLO \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DUMMY_GET_COUNT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DUMMY_ECHO \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DUMMY_TERMINATE_PROCESS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#ifndef PROCESS_TERMINATE
#define PROCESS_TERMINATE (0x0001)
#endif
